//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the drone_ollie package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __drone_ollie__DETECTOR_PARAMS2CONFIG_H__
#define __drone_ollie__DETECTOR_PARAMS2CONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace drone_ollie
{
  class detector_params2ConfigStatics;
  
  class detector_params2Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(detector_params2Config &config, const detector_params2Config &max, const detector_params2Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const detector_params2Config &config1, const detector_params2Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, detector_params2Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const detector_params2Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, detector_params2Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const detector_params2Config &config) const = 0;
      virtual void getValue(const detector_params2Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T detector_params2Config::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (detector_params2Config::* field);

      virtual void clamp(detector_params2Config &config, const detector_params2Config &max, const detector_params2Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const detector_params2Config &config1, const detector_params2Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, detector_params2Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const detector_params2Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, detector_params2Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const detector_params2Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const detector_params2Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, detector_params2Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, detector_params2Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<detector_params2Config::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(detector_params2Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("detector_on"==(*i)->name){detector_on = boost::any_cast<bool>(val);}
        if("nav_goal"==(*i)->name){nav_goal = boost::any_cast<int>(val);}
        if("nav_filter"==(*i)->name){nav_filter = boost::any_cast<double>(val);}
        if("hog_on"==(*i)->name){hog_on = boost::any_cast<bool>(val);}
        if("fps"==(*i)->name){fps = boost::any_cast<double>(val);}
        if("rot_inter"==(*i)->name){rot_inter = boost::any_cast<int>(val);}
        if("rectify"==(*i)->name){rectify = boost::any_cast<int>(val);}
        if("svm"==(*i)->name){svm = boost::any_cast<int>(val);}
        if("stride_x"==(*i)->name){stride_x = boost::any_cast<int>(val);}
        if("stride_y"==(*i)->name){stride_y = boost::any_cast<int>(val);}
        if("gamma_correction"==(*i)->name){gamma_correction = boost::any_cast<bool>(val);}
        if("sigma"==(*i)->name){sigma = boost::any_cast<double>(val);}
        if("levels"==(*i)->name){levels = boost::any_cast<int>(val);}
        if("hit_thresh"==(*i)->name){hit_thresh = boost::any_cast<double>(val);}
        if("grouping"==(*i)->name){grouping = boost::any_cast<bool>(val);}
        if("win_stride"==(*i)->name){win_stride = boost::any_cast<int>(val);}
        if("scale"==(*i)->name){scale = boost::any_cast<double>(val);}
        if("final_thresh"==(*i)->name){final_thresh = boost::any_cast<double>(val);}
        if("human_height_min"==(*i)->name){human_height_min = boost::any_cast<double>(val);}
        if("human_height_max"==(*i)->name){human_height_max = boost::any_cast<double>(val);}
        if("human_dist_min"==(*i)->name){human_dist_min = boost::any_cast<double>(val);}
        if("human_dist_max"==(*i)->name){human_dist_max = boost::any_cast<double>(val);}
        if("show_true"==(*i)->name){show_true = boost::any_cast<bool>(val);}
        if("show_false"==(*i)->name){show_false = boost::any_cast<bool>(val);}
      }
    }

    bool detector_on;
int nav_goal;
double nav_filter;
bool hog_on;
double fps;
int rot_inter;
int rectify;
int svm;
int stride_x;
int stride_y;
bool gamma_correction;
double sigma;
int levels;
double hit_thresh;
bool grouping;
int win_stride;
double scale;
double final_thresh;
double human_height_min;
double human_height_max;
double human_dist_min;
double human_dist_max;
bool show_true;
bool show_false;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool detector_on;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int nav_goal;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double nav_filter;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool hog_on;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double fps;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int rot_inter;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int rectify;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int svm;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int stride_x;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int stride_y;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool gamma_correction;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double sigma;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int levels;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double hit_thresh;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool grouping;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int win_stride;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double scale;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double final_thresh;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double human_height_min;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double human_height_max;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double human_dist_min;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double human_dist_max;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool show_true;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool show_false;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("detector_params2Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const detector_params2Config &__max__ = __getMax__();
      const detector_params2Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const detector_params2Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const detector_params2Config &__getDefault__();
    static const detector_params2Config &__getMax__();
    static const detector_params2Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const detector_params2ConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void detector_params2Config::ParamDescription<std::string>::clamp(detector_params2Config &config, const detector_params2Config &max, const detector_params2Config &min) const
  {
    return;
  }

  class detector_params2ConfigStatics
  {
    friend class detector_params2Config;
    
    detector_params2ConfigStatics()
    {
detector_params2Config::GroupDescription<detector_params2Config::DEFAULT, detector_params2Config> Default("Default", "", 0, 0, true, &detector_params2Config::groups);
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.detector_on = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.detector_on = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.detector_on = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("detector_on", "bool", 0, "Turn node on", "", &detector_params2Config::detector_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("detector_on", "bool", 0, "Turn node on", "", &detector_params2Config::detector_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.nav_goal = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.nav_goal = 3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.nav_goal = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("nav_goal", "int", 0, "...", "{'enum_description': '...', 'enum': [{'srcline': 13, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Ignore'}, {'srcline': 14, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'FilterHogInitially'}, {'srcline': 15, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'FilterHogAlways'}, {'srcline': 16, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'UseInstead'}]}", &detector_params2Config::nav_goal)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("nav_goal", "int", 0, "...", "{'enum_description': '...', 'enum': [{'srcline': 13, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Ignore'}, {'srcline': 14, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'FilterHogInitially'}, {'srcline': 15, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'FilterHogAlways'}, {'srcline': 16, 'description': '...', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'UseInstead'}]}", &detector_params2Config::nav_goal)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.nav_filter = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.nav_filter = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.nav_filter = 1.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("nav_filter", "double", 0, "", "", &detector_params2Config::nav_filter)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("nav_filter", "double", 0, "", "", &detector_params2Config::nav_filter)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.hog_on = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.hog_on = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.hog_on = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("hog_on", "bool", 1, "Turn detector on", "", &detector_params2Config::hog_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("hog_on", "bool", 1, "Turn detector on", "", &detector_params2Config::hog_on)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.fps = 0.25;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.fps = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.fps = 2.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("fps", "double", 0, "maximum", "", &detector_params2Config::fps)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("fps", "double", 0, "maximum", "", &detector_params2Config::fps)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.rot_inter = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.rot_inter = 5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.rot_inter = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("rot_inter", "int", 0, "Interpolation for Rotation", "{'enum_description': 'Set Interpolation Method', 'enum': [{'srcline': 25, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'INTER_NEAREST'}, {'srcline': 26, 'description': 'bilinear interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'LINEAR'}, {'srcline': 27, 'description': 'resampling using pixel area relation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'AREA'}, {'srcline': 28, 'description': 'bicubic interpolation over 4x4 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'CUBIC'}, {'srcline': 29, 'description': 'Lanczos interpolation over 8x8 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'LANCZOS4'}]}", &detector_params2Config::rot_inter)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("rot_inter", "int", 0, "Interpolation for Rotation", "{'enum_description': 'Set Interpolation Method', 'enum': [{'srcline': 25, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'INTER_NEAREST'}, {'srcline': 26, 'description': 'bilinear interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'LINEAR'}, {'srcline': 27, 'description': 'resampling using pixel area relation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'AREA'}, {'srcline': 28, 'description': 'bicubic interpolation over 4x4 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'CUBIC'}, {'srcline': 29, 'description': 'Lanczos interpolation over 8x8 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'LANCZOS4'}]}", &detector_params2Config::rot_inter)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.rectify = -1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.rectify = 5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.rectify = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("rectify", "int", 0, "Interpolation for Rotation", "{'enum_description': 'Set Interpolation Method', 'enum': [{'srcline': 35, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': -1, 'ctype': 'int', 'type': 'int', 'name': 'NO_RECTIFY'}, {'srcline': 36, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_INTER_NEAREST'}, {'srcline': 37, 'description': 'bilinear interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_LINEAR'}, {'srcline': 38, 'description': 'resampling using pixel area relation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_AREA'}, {'srcline': 39, 'description': 'bicubic interpolation over 4x4 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_CUBIC'}, {'srcline': 40, 'description': 'Lanczos interpolation over 8x8 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_LANCZOS4'}]}", &detector_params2Config::rectify)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("rectify", "int", 0, "Interpolation for Rotation", "{'enum_description': 'Set Interpolation Method', 'enum': [{'srcline': 35, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': -1, 'ctype': 'int', 'type': 'int', 'name': 'NO_RECTIFY'}, {'srcline': 36, 'description': 'nearest-neighbor interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_INTER_NEAREST'}, {'srcline': 37, 'description': 'bilinear interpolation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_LINEAR'}, {'srcline': 38, 'description': 'resampling using pixel area relation', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_AREA'}, {'srcline': 39, 'description': 'bicubic interpolation over 4x4 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_CUBIC'}, {'srcline': 40, 'description': 'Lanczos interpolation over 8x8 pixel neighborhood', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'RECTIFY_LANCZOS4'}]}", &detector_params2Config::rectify)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.svm = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.svm = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.svm = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("svm", "int", 0, "", "{'enum_description': '', 'enum': [{'srcline': 45, 'description': '', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Daimler'}, {'srcline': 46, 'description': '', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Default'}]}", &detector_params2Config::svm)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("svm", "int", 0, "", "{'enum_description': '', 'enum': [{'srcline': 45, 'description': '', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Daimler'}, {'srcline': 46, 'description': '', 'srcfile': '/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Default'}]}", &detector_params2Config::svm)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.stride_x = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.stride_x = 16;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.stride_x = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("stride_x", "int", 0, "", "", &detector_params2Config::stride_x)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("stride_x", "int", 0, "", "", &detector_params2Config::stride_x)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.stride_y = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.stride_y = 16;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.stride_y = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("stride_y", "int", 0, "", "", &detector_params2Config::stride_y)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("stride_y", "int", 0, "", "", &detector_params2Config::stride_y)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.gamma_correction = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.gamma_correction = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.gamma_correction = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("gamma_correction", "bool", 0, "", "", &detector_params2Config::gamma_correction)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("gamma_correction", "bool", 0, "", "", &detector_params2Config::gamma_correction)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.sigma = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.sigma = 30.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.sigma = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("sigma", "double", 0, "", "", &detector_params2Config::sigma)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("sigma", "double", 0, "", "", &detector_params2Config::sigma)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.levels = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.levels = 16;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.levels = 4;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("levels", "int", 0, "", "", &detector_params2Config::levels)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("levels", "int", 0, "", "", &detector_params2Config::levels)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.hit_thresh = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.hit_thresh = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.hit_thresh = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("hit_thresh", "double", 0, "example", "", &detector_params2Config::hit_thresh)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("hit_thresh", "double", 0, "example", "", &detector_params2Config::hit_thresh)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.grouping = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.grouping = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.grouping = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("grouping", "bool", 0, "Turn detector on", "", &detector_params2Config::grouping)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("grouping", "bool", 0, "Turn detector on", "", &detector_params2Config::grouping)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.win_stride = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.win_stride = 16;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.win_stride = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("win_stride", "int", 0, "example", "", &detector_params2Config::win_stride)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<int>("win_stride", "int", 0, "example", "", &detector_params2Config::win_stride)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.scale = 1.05;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.scale = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.scale = 1.3;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("scale", "double", 0, "example", "", &detector_params2Config::scale)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("scale", "double", 0, "example", "", &detector_params2Config::scale)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.final_thresh = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.final_thresh = 8.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.final_thresh = 0.8;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("final_thresh", "double", 0, "example", "", &detector_params2Config::final_thresh)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("final_thresh", "double", 0, "example", "", &detector_params2Config::final_thresh)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.human_height_min = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.human_height_min = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.human_height_min = 1.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_height_min", "double", 0, "example", "", &detector_params2Config::human_height_min)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_height_min", "double", 0, "example", "", &detector_params2Config::human_height_min)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.human_height_max = 0.1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.human_height_max = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.human_height_max = 2.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_height_max", "double", 0, "example", "", &detector_params2Config::human_height_max)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_height_max", "double", 0, "example", "", &detector_params2Config::human_height_max)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.human_dist_min = 0.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.human_dist_min = 25.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.human_dist_min = 4.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_dist_min", "double", 0, "example", "", &detector_params2Config::human_dist_min)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_dist_min", "double", 0, "example", "", &detector_params2Config::human_dist_min)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.human_dist_max = 0.5;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.human_dist_max = 25.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.human_dist_max = 8.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_dist_max", "double", 0, "example", "", &detector_params2Config::human_dist_max)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<double>("human_dist_max", "double", 0, "example", "", &detector_params2Config::human_dist_max)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.show_true = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.show_true = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.show_true = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("show_true", "bool", 0, "Turn detector on", "", &detector_params2Config::show_true)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("show_true", "bool", 0, "Turn detector on", "", &detector_params2Config::show_true)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.show_false = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.show_false = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.show_false = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("show_false", "bool", 0, "Turn detector on", "", &detector_params2Config::show_false)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(detector_params2Config::AbstractParamDescriptionConstPtr(new detector_params2Config::ParamDescription<bool>("show_false", "bool", 0, "Turn detector on", "", &detector_params2Config::show_false)));
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(detector_params2Config::AbstractGroupDescriptionConstPtr(new detector_params2Config::GroupDescription<detector_params2Config::DEFAULT, detector_params2Config>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<detector_params2Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<detector_params2Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<detector_params2Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    detector_params2Config __max__;
    detector_params2Config __min__;
    detector_params2Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const detector_params2ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static detector_params2ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &detector_params2Config::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const detector_params2Config &detector_params2Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const detector_params2Config &detector_params2Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const detector_params2Config &detector_params2Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<detector_params2Config::AbstractParamDescriptionConstPtr> &detector_params2Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<detector_params2Config::AbstractGroupDescriptionConstPtr> &detector_params2Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const detector_params2ConfigStatics *detector_params2Config::__get_statics__()
  {
    const static detector_params2ConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = detector_params2ConfigStatics::get_instance();
    
    return statics;
  }

//#line 13 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_Ignore = 0;
//#line 14 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_FilterHogInitially = 1;
//#line 15 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_FilterHogAlways = 2;
//#line 16 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_UseInstead = 3;
//#line 25 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_INTER_NEAREST = 0;
//#line 26 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_LINEAR = 1;
//#line 27 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_AREA = 2;
//#line 28 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_CUBIC = 3;
//#line 29 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_LANCZOS4 = 4;
//#line 35 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_NO_RECTIFY = -1;
//#line 36 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_RECTIFY_INTER_NEAREST = 0;
//#line 37 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_RECTIFY_LINEAR = 1;
//#line 38 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_RECTIFY_AREA = 2;
//#line 39 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_RECTIFY_CUBIC = 3;
//#line 40 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_RECTIFY_LANCZOS4 = 4;
//#line 45 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_Daimler = 0;
//#line 46 "/home/ollie/Dropbox/Code/ROS/drone_ollie/cfg/detector_params.cfg"
      const int detector_params2_Default = 1;
}

#endif // __DETECTOR_PARAMS2RECONFIGURATOR_H__
